import type { ArtefactRecord } from "./types";

/**
 * The Object Archive.
 *
 * A catalogue, not a gallery. Every object gets a catalogue number, a type, a
 * date range, a provenance line and an evidence record, whether or not the
 * object is in hand yet.
 *
 * `holding` is the important field:
 * - `held`   the object exists in the archive and can be photographed
 * - `wanted` a useful object may exist; public display groups these into a
 *            short, optional request rather than an owner checklist
 * - `lost`   the object is known to have existed and is known to be gone
 *
 * Catalogue numbers follow `MS-<year or XXXX>-<sequence>`. `XXXX` is an honest
 * statement that the object is undated, and should be replaced when it is not.
 */
export const artefacts: ArtefactRecord[] = [
  {
    id: "MS-1996-001",
    catalogue: "MS-1996-001",
    title: "Earliest surviving receipt or dated shop paper",
    objectType: "document",
    dateRange: "Date unknown",
    description:
      "The earliest address-specific shop paper that survives. Even an ordinary receipt could narrow the physical trading chronology without pretending to be an opening certificate.",
    provenance: "Possible: an unsorted shop or family file.",
    holding: "wanted",
    relatedIds: ["opening"],
    tags: ["opening", "paper", "dating evidence"],
    evidence: { status: "placeholder" },
    media: {
      id: "MS-1996-001-media",
      kind: "document",
      alt: "Catalogue space reserved for the earliest surviving receipt or dated shop paper",
      caption: "Wanted: the earliest surviving receipt, however faded.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-1996-002",
    catalogue: "MS-1996-002",
    title: "Earliest lease or trading paperwork",
    objectType: "document",
    dateRange: "Date unknown",
    description:
      "An early address-bearing document could narrow the first physical trading date and the name then in use. It need not be the original lease.",
    provenance: "Possible: an unsorted shop or family file.",
    holding: "wanted",
    relatedIds: ["opening", "before-cignall"],
    tags: ["opening", "paper", "dating evidence"],
    evidence: { status: "placeholder" },
    media: {
      id: "MS-1996-002-media",
      kind: "document",
      alt: "Catalogue space reserved for the earliest surviving lease or trading paperwork",
      caption: "Wanted: the earliest paperwork bearing the address.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-003",
    catalogue: "MS-XXXX-003",
    title: "Rob and Carla behind the counter",
    objectType: "photograph",
    dateRange: "Undated — any decade",
    description:
      "Any photograph of the two of them at work. Preferably several, spread across thirty years, so the room can show time passing rather than describe it.",
    provenance: "Expected: family album.",
    holding: "wanted",
    relatedIds: ["rob", "carla"],
    tags: ["portrait", "family"],
    evidence: { status: "placeholder", permission: "pending" },
    media: {
      id: "MS-XXXX-003-media",
      kind: "image",
      alt: "Catalogue space reserved for photographs of Rob and Carla behind the counter",
      caption: "Wanted: working photographs, not posed ones.",
      evidence: { status: "placeholder", permission: "pending" },
    },
  },
  {
    id: "MS-XXXX-004",
    catalogue: "MS-XXXX-004",
    title: "Smokey's Frankston House Lotto material",
    objectType: "signage",
    dateRange: "Pre-Cignall era, dates unknown",
    description:
      "Anything at all carrying the earlier trading identity: a sign, a bag, a letterhead, a docket book, a photograph with the fascia legible.",
    provenance: "Expected: on site, or in the back room.",
    holding: "wanted",
    relatedIds: ["before-cignall"],
    tags: ["signage", "pre-cignall", "dating evidence"],
    evidence: { status: "placeholder" },
    media: {
      id: "MS-XXXX-004-media",
      kind: "object",
      alt: "Catalogue space reserved for early Smokey's Frankston House Lotto material",
      caption: "Wanted: the shop's name before this one.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-005",
    catalogue: "MS-XXXX-005",
    title: "Previous shopfront signage",
    objectType: "signage",
    dateRange: "Undated",
    description:
      "Removed fascia, light boxes, window vinyl or the sign that came down when the next one went up. Old signage is usually in a shed rather than a skip.",
    provenance: "Expected: on site.",
    holding: "wanted",
    relatedIds: ["before-cignall"],
    tags: ["signage", "shopfront"],
    evidence: { status: "placeholder" },
    media: {
      id: "MS-XXXX-005-media",
      kind: "object",
      alt: "Catalogue space reserved for previous shopfront signage",
      caption: "Wanted: whatever came down off the front of the building.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-006",
    catalogue: "MS-XXXX-006",
    title: "Key cutting machine and blanks",
    objectType: "tool",
    dateRange: "In service, dates unknown",
    description:
      "The machine, the board of blanks and the noise the whole street knew. A working object with thirty years of metal dust on it.",
    provenance: "Expected: on site.",
    holding: "wanted",
    relatedIds: ["everything-counter"],
    tags: ["counter", "service", "tool"],
    evidence: { status: "placeholder" },
    media: {
      id: "MS-XXXX-006-media",
      kind: "object",
      alt: "Catalogue space reserved for the key cutting machine and its board of blanks",
      caption: "Wanted: the machine, photographed where it stands.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-007",
    catalogue: "MS-XXXX-007",
    title: "Specialist catalogue / surviving stock",
    objectType: "object",
    dateRange: "Unknown",
    description:
      "Archived 2016 pages document specialist pipe and tobacco categories online. Any surviving cabinet, catalogue or stock photograph could show what was also present in the physical shop.",
    provenance: "Online catalogue documented; physical stock remains unconfirmed.",
    holding: "wanted",
    relatedIds: ["everything-counter"],
    tags: ["tobacco", "trade", "unconfirmed"],
    evidence: {
      status: "needs-confirmation",
      note: "The online catalogue is documented. This object slot does not claim that every category was stocked in-store.",
      sourceIds: ["tobacco-blends-home-2016", "tobacco-blends-about-2016"],
    },
    media: {
      id: "MS-XXXX-007-media",
      kind: "object",
      alt: "Catalogue space reserved for specialist pipe stock or fittings",
      caption: "Bonus: one catalogue, cabinet or stock photograph, if it already exists.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-008",
    catalogue: "MS-XXXX-008",
    title: "Photographs identifying the monkeys",
    objectType: "photograph",
    dateRange: "Before c. 2015",
    description:
      "Any image that can identify Ziggie, Archie or a reported replacement. Customer photographs count; exact dates are not required.",
    provenance: "Expected: shop, family album, or the public.",
    holding: "wanted",
    relatedIds: ["ziggy", "the-interregnum", "monkey-heist"],
    tags: ["monkey", "folklore"],
    evidence: { status: "placeholder" },
    media: {
      id: "MS-XXXX-008-media",
      kind: "image",
      alt: "Catalogue space reserved for photographs identifying Ziggie, Archie or a replacement",
      caption: "Essential: one monkey image or material. A phone photograph is enough.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-2016-009",
    catalogue: "MS-2016-009",
    title: "Press clipping: the missing/replaced monkey",
    objectType: "press",
    dateRange: "Published 2 January 2016",
    description:
      "The full Leader/Herald Sun report behind the indexed disappearance, search/reward, non-recovery and replacement lead.",
    provenance: "Herald Sun / Leader South East; full article copy still sought.",
    holding: "wanted",
    relatedIds: ["monkey-heist", "ziggy"],
    tags: ["monkey", "press", "disappearance"],
    evidence: {
      status: "strongly-supported",
      sourceIds: ["herald-ziggie-2016"],
    },
    media: {
      id: "MS-2016-009-media",
      kind: "document",
      alt: "Catalogue space reserved for the full January 2016 Ziggie article",
      caption: "Essential: an owner-held clipping is welcome; public archive retrieval remains an internal research task.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-010",
    catalogue: "MS-XXXX-010",
    title: "Reward notice",
    objectType: "ephemera",
    dateRange: "Before 2 January 2016",
    description:
      "If a notice went in the window asking for the monkey back, it is one of the best objects in this entire archive.",
    provenance: "Expected: shop window, or nowhere.",
    holding: "wanted",
    relatedIds: ["monkey-heist"],
    tags: ["monkey", "window", "reward"],
    evidence: { status: "placeholder", sourceIds: ["herald-ziggie-2016"] },
    media: {
      id: "MS-XXXX-010-media",
      kind: "document",
      alt: "Catalogue space reserved for the reward notice for the missing monkey",
      caption: "Wanted: the notice, or a photograph of it in the window.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-011",
    catalogue: "MS-XXXX-011",
    title: "The monkey named Ziggie",
    objectType: "object",
    dateRange: "Missing by 2 January 2016",
    description:
      "The figure named in the published disappearance/replacement lead. The source says it was not recovered; it does not establish that this was the first shop monkey or settle the Archie relationship.",
    provenance: "Reported missing and not recovered.",
    holding: "lost",
    relatedIds: ["ziggy", "monkey-heist"],
    tags: ["monkey", "lost", "folklore"],
    evidence: {
      status: "strongly-supported",
      note: "Non-recovery is supported by indexed published wording. Identity, succession and detailed circumstances remain unresolved.",
      sourceIds: ["herald-ziggie-2016"],
    },
    media: {
      id: "MS-XXXX-011-media",
      kind: "object",
      alt: "Catalogue space left deliberately empty for the missing monkey named Ziggie",
      caption: "Not held. Not expected.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-012",
    catalogue: "MS-XXXX-012",
    title: "Blackboard sayings",
    objectType: "artwork",
    dateRange: "Ongoing",
    description:
      "Photographs of the board across the years. Individually disposable, collectively the shop's own writing.",
    provenance: "Expected: shop phone, shop social media, customer photographs.",
    holding: "wanted",
    relatedIds: ["blackboard"],
    tags: ["board", "voice", "handwriting"],
    evidence: { status: "needs-confirmation", sourceIds: ["shop-facebook-profile"] },
    media: {
      id: "MS-XXXX-012-media",
      kind: "image",
      alt: "Catalogue space reserved for photographs of the shop's blackboard sayings",
      caption: "Wanted: as many as survive, dated where possible.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-013",
    catalogue: "MS-XXXX-013",
    title: "Tatts and Lotto point-of-sale material",
    objectType: "ephemera",
    dateRange: "Dates unknown",
    description:
      "Division One window banners, jackpot posters, counter mats and terminal signage. The visual language of thirty years of hoping.",
    provenance: "Expected: on site.",
    holding: "wanted",
    relatedIds: ["million-2022", "thirty-years"],
    tags: ["lotto", "signage", "window"],
    evidence: { status: "placeholder" },
    media: {
      id: "MS-XXXX-013-media",
      kind: "object",
      alt: "Catalogue space reserved for Tatts and Lotto point-of-sale material",
      caption: "Wanted: the loudest paper in the shop.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-014",
    catalogue: "MS-XXXX-014",
    title: "Staff photographs",
    objectType: "photograph",
    dateRange: "1996 onward",
    description:
      "Christmases, birthdays, first shifts, last shifts. Each one needs the name of everybody in it and their permission before it goes on a wall.",
    provenance: "Expected: shop, family and former staff.",
    holding: "wanted",
    relatedIds: ["staff-early", "staff-long-service"],
    tags: ["staff", "portrait"],
    evidence: { status: "placeholder", permission: "pending" },
    media: {
      id: "MS-XXXX-014-media",
      kind: "image",
      alt: "Catalogue space reserved for staff photographs spanning three decades",
      caption: "Wanted: staff dinners, first shifts, last shifts.",
      evidence: { status: "placeholder", permission: "pending" },
    },
  },
  {
    id: "MS-XXXX-015",
    catalogue: "MS-XXXX-015",
    title: "Uniforms and shop-branded clothing",
    objectType: "textile",
    dateRange: "Undated",
    description:
      "Polo shirts, aprons, jackets. Branded clothing dates a business faster than paperwork, because nobody throws it out and nobody wears it after.",
    provenance: "Expected: back room.",
    holding: "wanted",
    tags: ["uniform", "branding", "dating evidence"],
    evidence: { status: "placeholder" },
    media: {
      id: "MS-XXXX-015-media",
      kind: "object",
      alt: "Catalogue space reserved for shop uniforms and branded clothing",
      caption: "Wanted: anything with the old logo on it.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-2026-016",
    catalogue: "MS-2026-016",
    title: "Tenth Division One shop material",
    objectType: "ephemera",
    dateRange: "June 2026",
    description:
      "A window notice, banner or counter item, if one was made for the tenth Division One win in the shop's thirtieth-year frame.",
    provenance: "Possible: on site, recent.",
    holding: "wanted",
    relatedIds: ["thirty-years"],
    tags: ["lotto", "window", "anniversary"],
    evidence: {
      status: "placeholder",
      note: "The win is sourced; this slot does not claim that physical display material exists.",
      sourceIds: ["lott-2026-tenth-win"],
    },
    media: {
      id: "MS-2026-016-media",
      kind: "object",
      alt: "Catalogue space reserved for any shop material made for the tenth Division One win",
      caption: "Useful: a phone photograph, if this material exists.",
      evidence: { status: "placeholder" },
    },
  },
];
