import type { ArtefactRecord } from "./types";

/**
 * The Object Archive.
 *
 * A catalogue, not a gallery. Every object gets a catalogue number, a type, a
 * date range, a provenance line and an evidence record, whether or not the
 * object is in hand yet.
 *
 * `holding` is the important field:
 * - `held`   the object exists in the archive and can be photographed
 * - `wanted` the object is expected to exist; this is the request to Rob
 * - `lost`   the object is known to have existed and is known to be gone
 *
 * Catalogue numbers follow `MS-<year or XXXX>-<sequence>`. `XXXX` is an honest
 * statement that the object is undated, and should be replaced when it is not.
 */
export const artefacts: ArtefactRecord[] = [
  {
    id: "MS-1996-001",
    catalogue: "MS-1996-001",
    title: "First till receipt",
    objectType: "document",
    dateRange: "1996",
    description:
      "The first transaction the shop ever recorded. If the roll survives, it dates the opening better than any memory can.",
    provenance: "Expected: Rob and Carla's own records.",
    holding: "wanted",
    relatedIds: ["opening"],
    tags: ["opening", "paper", "dating evidence"],
    evidence: { status: "placeholder", sourceIds: ["shop-ledger"] },
    media: {
      id: "MS-1996-001-media",
      kind: "document",
      alt: "Catalogue space reserved for a photograph of the first till receipt",
      caption: "Wanted: the earliest surviving receipt, however faded.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-1996-002",
    catalogue: "MS-1996-002",
    title: "Original lease or first trading paperwork",
    objectType: "document",
    dateRange: "c. 1996",
    description:
      "The document most likely to settle the opening date, the original trading name and the shape of the first tenancy at 8 Thompson Street.",
    provenance: "Expected: Rob and Carla's own records.",
    holding: "wanted",
    relatedIds: ["opening", "before-cignall"],
    tags: ["opening", "paper", "dating evidence"],
    evidence: { status: "placeholder", sourceIds: ["shop-ledger"] },
    media: {
      id: "MS-1996-002-media",
      kind: "document",
      alt: "Catalogue space reserved for the original lease or first trading paperwork",
      caption: "Wanted: the earliest paperwork bearing the address.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-003",
    catalogue: "MS-XXXX-003",
    title: "Rob and Carla behind the counter",
    objectType: "photograph",
    dateRange: "Undated — any decade",
    description:
      "Any photograph of the two of them at work. Preferably several, spread across thirty years, so the room can show time passing rather than describe it.",
    provenance: "Expected: family album.",
    holding: "wanted",
    relatedIds: ["rob", "carla"],
    tags: ["portrait", "family"],
    evidence: { status: "placeholder", permission: "pending" },
    media: {
      id: "MS-XXXX-003-media",
      kind: "image",
      alt: "Catalogue space reserved for photographs of Rob and Carla behind the counter",
      caption: "Wanted: working photographs, not posed ones.",
      evidence: { status: "placeholder", permission: "pending" },
    },
  },
  {
    id: "MS-XXXX-004",
    catalogue: "MS-XXXX-004",
    title: "Smokey's Frankston House Lotto material",
    objectType: "signage",
    dateRange: "Pre-Cignall era, dates unknown",
    description:
      "Anything at all carrying the earlier trading identity: a sign, a bag, a letterhead, a docket book, a photograph with the fascia legible.",
    provenance: "Expected: on site, or in the back room.",
    holding: "wanted",
    relatedIds: ["before-cignall"],
    tags: ["signage", "pre-cignall", "dating evidence"],
    evidence: { status: "needs-confirmation", sourceIds: ["shop-ledger"] },
    media: {
      id: "MS-XXXX-004-media",
      kind: "object",
      alt: "Catalogue space reserved for early Smokey's Frankston House Lotto material",
      caption: "Wanted: the shop's name before this one.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-005",
    catalogue: "MS-XXXX-005",
    title: "Previous shopfront signage",
    objectType: "signage",
    dateRange: "Undated",
    description:
      "Removed fascia, light boxes, window vinyl or the sign that came down when the next one went up. Old signage is usually in a shed rather than a skip.",
    provenance: "Expected: on site.",
    holding: "wanted",
    relatedIds: ["before-cignall"],
    tags: ["signage", "shopfront"],
    evidence: { status: "placeholder", sourceIds: ["shop-ledger"] },
    media: {
      id: "MS-XXXX-005-media",
      kind: "object",
      alt: "Catalogue space reserved for previous shopfront signage",
      caption: "Wanted: whatever came down off the front of the building.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-006",
    catalogue: "MS-XXXX-006",
    title: "Key cutting machine and blanks",
    objectType: "tool",
    dateRange: "In service, dates unknown",
    description:
      "The machine, the board of blanks and the noise the whole street knew. A working object with thirty years of metal dust on it.",
    provenance: "Expected: on site.",
    holding: "wanted",
    relatedIds: ["everything-counter"],
    tags: ["counter", "service", "tool"],
    evidence: { status: "needs-confirmation", sourceIds: ["shop-ledger"] },
    media: {
      id: "MS-XXXX-006-media",
      kind: "object",
      alt: "Catalogue space reserved for the key cutting machine and its board of blanks",
      caption: "Wanted: the machine, photographed where it stands.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-007",
    catalogue: "MS-XXXX-007",
    title: "Specialist pipe stock and fittings",
    objectType: "object",
    dateRange: "Unknown",
    description:
      "A lead worth chasing: that the shop carried a serious pipe trade at some point. Stock, a cabinet, a catalogue or a supplier invoice would confirm it.",
    provenance: "Unconfirmed.",
    holding: "wanted",
    relatedIds: ["everything-counter"],
    tags: ["tobacco", "trade", "unconfirmed"],
    evidence: {
      status: "needs-confirmation",
      note: "Reported lead only. Do not describe a pipe trade the archive has not evidenced.",
      sourceIds: ["shop-ledger", "interview-rob"],
    },
    media: {
      id: "MS-XXXX-007-media",
      kind: "object",
      alt: "Catalogue space reserved for specialist pipe stock or fittings",
      caption: "Wanted: evidence that this trade existed.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-008",
    catalogue: "MS-XXXX-008",
    title: "Photographs of the original monkey",
    objectType: "photograph",
    dateRange: "Before c. 2015",
    description:
      "Any image showing Ziggy in position outside the shop. Customer photographs count, and are probably where this will actually be found.",
    provenance: "Expected: shop, family album, or the public.",
    holding: "wanted",
    relatedIds: ["ziggy", "monkey-arrives", "monkey-heist"],
    tags: ["monkey", "folklore"],
    evidence: { status: "placeholder", sourceIds: ["shop-social"] },
    media: {
      id: "MS-XXXX-008-media",
      kind: "image",
      alt: "Catalogue space reserved for photographs of the original monkey",
      caption: "Wanted: proof of what Ziggy actually looked like.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-2015-009",
    catalogue: "MS-2015-009",
    title: "Press clipping: the monkey theft",
    objectType: "press",
    dateRange: "c. 2015",
    description:
      "The local newspaper report of the theft and the replacement. Masthead, date and page number are all still unknown.",
    provenance: "Expected: local press archive, or a copy kept in the shop.",
    holding: "wanted",
    relatedIds: ["monkey-heist", "ziggy"],
    tags: ["monkey", "press", "theft"],
    evidence: {
      status: "needs-confirmation",
      sourceIds: ["local-press-monkey"],
    },
    media: {
      id: "MS-2015-009-media",
      kind: "document",
      alt: "Catalogue space reserved for the newspaper clipping about the monkey theft",
      caption: "Wanted: the page, with the masthead and date visible.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-2015-010",
    catalogue: "MS-2015-010",
    title: "Reward notice",
    objectType: "ephemera",
    dateRange: "c. 2015",
    description:
      "If a notice went in the window asking for the monkey back, it is one of the best objects in this entire archive.",
    provenance: "Expected: shop window, or nowhere.",
    holding: "wanted",
    relatedIds: ["monkey-heist"],
    tags: ["monkey", "window", "theft"],
    evidence: { status: "placeholder", sourceIds: ["local-press-monkey"] },
    media: {
      id: "MS-2015-010-media",
      kind: "document",
      alt: "Catalogue space reserved for the reward notice for the missing monkey",
      caption: "Wanted: the notice, or a photograph of it in the window.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-011",
    catalogue: "MS-XXXX-011",
    title: "The original monkey",
    objectType: "object",
    dateRange: "Unknown — removed c. 2015",
    description:
      "The object itself. Taken from outside the shop and, as far as anyone here knows, never recovered. Catalogued as lost, because a museum records what it does not have.",
    provenance: "Stolen.",
    holding: "lost",
    relatedIds: ["ziggy", "monkey-heist"],
    tags: ["monkey", "lost", "folklore"],
    evidence: {
      status: "needs-confirmation",
      note: "Recovery status unconfirmed. If the original was ever returned, this record changes entirely.",
      sourceIds: ["local-press-monkey", "interview-rob"],
    },
    media: {
      id: "MS-XXXX-011-media",
      kind: "object",
      alt: "Catalogue space left deliberately empty for the stolen monkey",
      caption: "Not held. Not expected.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-012",
    catalogue: "MS-XXXX-012",
    title: "Blackboard sayings",
    objectType: "artwork",
    dateRange: "Ongoing",
    description:
      "Photographs of the board across the years. Individually disposable, collectively the shop's own writing.",
    provenance: "Expected: shop phone, shop social media, customer photographs.",
    holding: "wanted",
    relatedIds: ["blackboard"],
    tags: ["board", "voice", "handwriting"],
    evidence: { status: "needs-confirmation", sourceIds: ["shop-social"] },
    media: {
      id: "MS-XXXX-012-media",
      kind: "image",
      alt: "Catalogue space reserved for photographs of the shop's blackboard sayings",
      caption: "Wanted: as many as survive, dated where possible.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-013",
    catalogue: "MS-XXXX-013",
    title: "Tatts and Lotto point-of-sale material",
    objectType: "ephemera",
    dateRange: "1990s onward",
    description:
      "Division One window banners, jackpot posters, counter mats and terminal signage. The visual language of thirty years of hoping.",
    provenance: "Expected: on site.",
    holding: "wanted",
    relatedIds: ["million-2022", "thirty-years"],
    tags: ["lotto", "signage", "window"],
    evidence: { status: "placeholder", sourceIds: ["shop-ledger"] },
    media: {
      id: "MS-XXXX-013-media",
      kind: "object",
      alt: "Catalogue space reserved for Tatts and Lotto point-of-sale material",
      caption: "Wanted: the loudest paper in the shop.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-XXXX-014",
    catalogue: "MS-XXXX-014",
    title: "Staff photographs",
    objectType: "photograph",
    dateRange: "1996 onward",
    description:
      "Christmases, birthdays, first shifts, last shifts. Each one needs the name of everybody in it and their permission before it goes on a wall.",
    provenance: "Expected: shop, family and former staff.",
    holding: "wanted",
    relatedIds: ["staff-early", "staff-long-service"],
    tags: ["staff", "portrait"],
    evidence: { status: "placeholder", permission: "pending" },
    media: {
      id: "MS-XXXX-014-media",
      kind: "image",
      alt: "Catalogue space reserved for staff photographs spanning three decades",
      caption: "Wanted: staff dinners, first shifts, last shifts.",
      evidence: { status: "placeholder", permission: "pending" },
    },
  },
  {
    id: "MS-XXXX-015",
    catalogue: "MS-XXXX-015",
    title: "Uniforms and shop-branded clothing",
    objectType: "textile",
    dateRange: "Undated",
    description:
      "Polo shirts, aprons, jackets. Branded clothing dates a business faster than paperwork, because nobody throws it out and nobody wears it after.",
    provenance: "Expected: back room.",
    holding: "wanted",
    tags: ["uniform", "branding", "dating evidence"],
    evidence: { status: "placeholder", sourceIds: ["shop-ledger"] },
    media: {
      id: "MS-XXXX-015-media",
      kind: "object",
      alt: "Catalogue space reserved for shop uniforms and branded clothing",
      caption: "Wanted: anything with the old logo on it.",
      evidence: { status: "placeholder" },
    },
  },
  {
    id: "MS-2026-016",
    catalogue: "MS-2026-016",
    title: "Tenth Division One window notice",
    objectType: "ephemera",
    dateRange: "June 2026",
    description:
      "The material that went up when the tenth Division One win landed in the shop's thirtieth year. The only artefact in this catalogue with a confirmed date attached to a confirmed event.",
    provenance: "Expected: on site, recent.",
    holding: "wanted",
    relatedIds: ["thirty-years"],
    tags: ["lotto", "window", "anniversary"],
    evidence: {
      status: "verified",
      note: "The win is sourced; the physical material has not yet been collected.",
      sourceIds: ["lott-2026-tenth-win"],
    },
    media: {
      id: "MS-2026-016-media",
      kind: "object",
      alt: "Catalogue space reserved for the tenth Division One window notice",
      caption: "Wanted: photograph it before it comes down.",
      evidence: { status: "placeholder" },
    },
  },
];
