import { sources } from "./sources";
import type { ExhibitionContent, LedgerEntry } from "./types";

const pendingWin = (number: number): LedgerEntry => ({
  number,
  evidence: {
    status: "placeholder",
    note: "Date, draw, prize and customer story await documentary confirmation.",
  },
});

export const exhibition: ExhibitionContent = {
  navigation: [
    { href: "#story", label: "The story" },
    { href: "#monkey", label: "The monkey" },
    { href: "#ledger", label: "The ten" },
    { href: "#ask-ziggy", label: "Ask Ziggy" },
    { href: "#counter", label: "The counter" },
    { href: "#visit", label: "Visit" },
  ],
  timeline: [
    {
      id: "opening",
      year: "1996",
      eyebrow: "The first morning",
      title: "The doors open in Frankston",
      body: "The family-run agency begins. The precise opening date, original trading name and first shop photograph belong in the archive before this panel is final.",
      evidence: {
        status: "research-lead",
        note: "The 2026 anniversary is verified; the exact first trading day still needs Rob and Carla's records.",
        sourceIds: ["lott-2026-tenth-win"],
      },
      media: {
        id: "first-shopfront",
        kind: "image",
        alt: "Archive space reserved for the earliest known shopfront photograph",
        caption: "Wanted: earliest shopfront, counter or first-day photograph.",
        evidence: { status: "placeholder" },
      },
    },
    {
      id: "before-cignall",
      year: "1996–?",
      eyebrow: "Before the current sign",
      title: "The names above the same counter",
      body: "Smokey's, Cignall and The Monkey Shop are all part of the working title history. The order and dates are deliberately left open until invoices, signs or photographs settle it.",
      evidence: { status: "research-lead" },
    },
    {
      id: "monkey-heist",
      year: "2015–16",
      eyebrow: "Local folklore",
      title: "The great monkey heist",
      body: "A chapter for the original monkey, his disappearance and the replacement. Newspaper clipping, reward notice and Rob's account are still needed before publication.",
      evidence: { status: "research-lead" },
      media: {
        id: "heist-clipping",
        kind: "document",
        alt: "Archive space reserved for a newspaper clipping about the missing monkey",
        caption: "Wanted: clipping, reward poster or a photograph of the original monkey.",
        evidence: { status: "placeholder" },
      },
    },
    {
      id: "million-2022",
      year: "2022",
      eyebrow: "A ticket in a wallet",
      title: "$1 million discovered on a coffee run",
      body: "A Rosebud man discovered that a ticket bought at 8 Thompson Street had won Division One in TattsLotto draw 4223.",
      evidence: { status: "verified", sourceIds: ["lott-2022-million"] },
    },
    {
      id: "thirty-years",
      year: "2026",
      eyebrow: "Thirty years",
      title: "The tenth win arrives in anniversary month",
      body: "The agency marked thirty years as its tenth Division One entry delivered $3,126,800.49. The winner was on an exercise bike when the call arrived.",
      evidence: { status: "verified", sourceIds: ["lott-2026-tenth-win"] },
    },
  ],
  lore: [
    {
      id: "species",
      label: "Species",
      value: "Shopfront monkey",
      body: "Known to stand watch over Thompson Street and attract a mythology larger than the sign above him.",
      evidence: { status: "research-lead" },
    },
    {
      id: "habitat",
      label: "Habitat",
      value: "8 Thompson Street",
      body: "A verified address and the fixed point around which the exhibition turns.",
      evidence: { status: "verified", sourceIds: ["lott-2026-tenth-win"] },
    },
    {
      id: "nickname",
      label: "Known alias",
      value: "The Lucky Monkey Shop",
      body: "Rob told The Lott that this is what customers call the family-run agency.",
      evidence: { status: "verified", sourceIds: ["lott-2026-tenth-win"] },
    },
    {
      id: "behaviour",
      label: "Known behaviour",
      value: "Unsolicited advice",
      body: "A playful exhibition voice inspired by the shop's saying-board and quote tradition; the full chronology still needs primary material.",
      evidence: { status: "research-lead" },
    },
  ],
  ledger: [
    pendingWin(1),
    pendingWin(2),
    pendingWin(3),
    pendingWin(4),
    pendingWin(5),
    pendingWin(6),
    pendingWin(7),
    pendingWin(8),
    pendingWin(9),
    {
      number: 10,
      date: "13 June 2026",
      game: "TattsLotto",
      draw: "4685",
      prize: "$3,126,800.49",
      entry: "12-game QuickPick",
      story: "The call found the winner on an exercise bike. The win meant a home of his own and help for family.",
      evidence: { status: "verified", sourceIds: ["lott-2026-tenth-win"] },
    },
  ],
  lineage: [
    {
      id: "ziggy",
      name: "Ziggy",
      era: "Era to confirm",
      role: "The original legend",
      body: "The older monkey in the shop's folklore. Spelling, arrival date, disappearance and replacement history remain open research questions.",
      evidence: { status: "research-lead" },
      media: {
        id: "ziggy-portrait",
        kind: "image",
        alt: "Archive space reserved for a portrait of Ziggy",
        caption: "Wanted: the clearest recognisable portrait of Ziggy.",
        evidence: { status: "placeholder" },
      },
    },
    {
      id: "archie",
      name: "Archie",
      era: "Current",
      role: "Keeper of the door",
      body: "Named by Rob in the official account of the agency's tenth Division One win.",
      evidence: { status: "verified", sourceIds: ["lott-2026-tenth-win"] },
      media: {
        id: "archie-portrait",
        kind: "image",
        alt: "Archive space reserved for a current portrait of Archie outside the shop",
        caption: "Wanted: a current full-length portrait outside 8 Thompson Street.",
        evidence: { status: "placeholder" },
      },
    },
  ],
  counterStories: [
    {
      id: "saturday-regular",
      title: "The Saturday regular",
      prompt: "Who came in every week for years, and what did everyone know before they reached the counter?",
      evidence: { status: "placeholder" },
    },
    {
      id: "children-grown",
      title: "The kids grew up",
      prompt: "Which customers did Rob and Carla first meet as children, then later serve as adults or parents?",
      evidence: { status: "placeholder" },
    },
    {
      id: "thing-they-still-ask-for",
      title: "Still asking for it",
      prompt: "What discontinued thing does someone still ask for, years after it left the shelf?",
      evidence: { status: "placeholder" },
    },
    {
      id: "counter-laugh",
      title: "The line everyone remembers",
      prompt: "What is the most repeated joke, saying or bit of advice ever delivered across this counter?",
      evidence: { status: "placeholder" },
    },
  ],
  people: [
    {
      id: "rob",
      name: "Rob",
      role: "Owner · storyteller · keeper of the key",
      years: "Thirty years",
      memoryPrompt: "Ask Rob for the first morning, the strangest request and the object he could never throw away.",
      evidence: { status: "verified", sourceIds: ["lott-2026-tenth-win"] },
      media: {
        id: "rob-portrait",
        kind: "image",
        alt: "Portrait space reserved for Rob behind the counter",
        caption: "Commission: Rob behind the counter, looking toward the door.",
        evidence: { status: "placeholder" },
      },
    },
    {
      id: "carla",
      name: "Carla",
      role: "Family business · role and preferred credit to confirm",
      years: "Archive interview required",
      memoryPrompt: "Ask Carla what changed, what never did, and which photograph tells the real story.",
      evidence: { status: "research-lead" },
      media: {
        id: "carla-portrait",
        kind: "image",
        alt: "Portrait space reserved for Carla in the shop",
        caption: "Commission: Carla in the place she chooses to be remembered.",
        evidence: { status: "placeholder" },
      },
    },
    {
      id: "staff-archive",
      name: "The gang",
      role: "Past and present staff",
      memoryPrompt: "Collect names, years, nicknames, first-shift memories and permission for every photograph.",
      evidence: { status: "placeholder" },
      media: {
        id: "staff-group",
        kind: "image",
        alt: "Archive space reserved for staff photographs across three decades",
        caption: "Wanted: staff dinners, birthdays, first shifts and last shifts.",
        evidence: { status: "placeholder" },
      },
    },
  ],
  community: [
    {
      id: "small-yeses",
      title: "The small yeses",
      detail: "Raffle prizes, local clubs, school requests, collections and fundraisers—record each with a date, object and permission rather than a boast.",
      evidence: { status: "placeholder" },
    },
    {
      id: "services",
      title: "Everything at the counter",
      detail: "Build a dated inventory of newspapers, Lotto, key cutting, dry-cleaning and other services only after invoices, signs or Rob and Carla confirm them.",
      evidence: { status: "research-lead" },
    },
    {
      id: "frankston",
      title: "Frankston changed around it",
      detail: "Collect the shopfront views, neighbouring businesses and street details that show Thompson Street changing over thirty years.",
      evidence: { status: "placeholder" },
    },
  ],
  sources,
};
