import type { Source } from "./types";

/**
 * Public sources recovered for the exhibition.
 *
 * Notes state what each source can prove and, just as importantly, what it
 * cannot. Registry dates, archived-web dates and shop-opening dates remain
 * separate throughout the exhibition.
 */
export const sources: Source[] = [
  {
    id: "abr-greycliffs-history",
    label: "Historical details for ABN 53 073 538 726",
    publisher: "Australian Business Register",
    kind: "public-record",
    url: "https://abr.business.gov.au/AbnHistory/View/53073538726",
    retrievedOn: "2026-08-22",
    note: "Documents the company, ABN, GST, business-name and recorded trading-name chronology. It does not document a shop-opening day or shopfront-sign sequence.",
  },
  {
    id: "tobacco-blends-home-2016",
    label: "Archived Tobacco Blends home page · 19 January 2016",
    publisher: "Internet Archive / Tobacco Blends",
    kind: "public-record",
    url: "https://web.archive.org/web/20160119184606/https://www.tobaccoblends.com.au/",
    retrievedOn: "2026-08-22",
    note: "Documents a dated online catalogue and Greycliffs attribution. It does not prove that every category was stocked at 8 Thompson Street.",
  },
  {
    id: "tobacco-blends-contact-2016",
    label: "Archived Tobacco Blends contact page · 3 March 2016",
    publisher: "Internet Archive / Tobacco Blends",
    kind: "public-record",
    url: "https://web.archive.org/web/20160303055845/https://www.tobaccoblends.com.au/contact/",
    retrievedOn: "2026-08-22",
    note: "The first directly dated address-specific public web evidence recovered in this research pass: Tobacco Blends Retail Store / Cignall Tobacconist at 8 Thompson Street.",
  },
  {
    id: "tobacco-blends-about-2016",
    label: "Archived Tobacco Blends about page · 3 March 2016",
    publisher: "Internet Archive / Tobacco Blends",
    kind: "public-record",
    url: "https://web.archive.org/web/20160303055818/https://www.tobaccoblends.com.au/about/",
    retrievedOn: "2026-08-22",
    note: "Publicly describes Rob, Carla and their team as running the Frankston tobacconist for almost twenty years. That retrospective approximation is not an exact opening date.",
  },
  {
    id: "cignall-2016-win",
    label: "Tatts media release 4/4/16 · Frankston millionaire to hit the road",
    publisher: "Cignall Frankston",
    kind: "social",
    url: "https://www.facebook.com/cignall/posts/tatts-media-release-4416-frankston-millionaire-to-hit-the-roadforget-life-in-the/10154116654199586/",
    retrievedOn: "2026-08-22",
    note: "Retailer-side republication documenting the winner story, prize, outlet and address; it also records Rob calling the shop mascot Archie. The original Tatts release is still sought.",
  },
  {
    id: "lotterywest-3621",
    label: "Saturday Lotto draw 3621 results · 2 April 2016",
    publisher: "Lotterywest",
    kind: "official",
    url: "https://www.oz.lotterywest.com/saturday-lotto/results/draw/3621",
    retrievedOn: "2026-08-22",
    note: "Documents the draw date, number, three Division One entries and $1,380,313.01 dividend.",
  },
  {
    id: "herald-ziggie-2016",
    label: "New-look Ziggie back in place at Cignall Frankston · 2 January 2016",
    publisher: "Herald Sun / Leader South East",
    kind: "press",
    url: "https://www.heraldsun.com.au/leader/south-east/newlook-ziggie-back-in-place-at-cignall-frankston/news-story/7d417eed15ed95866e7f46836ace4d59",
    retrievedOn: "2026-08-22",
    note: "Search-indexed lead supports disappearance, search/reward, non-recovery and replacement. The full article was not retrieved, so detailed circumstances remain unresolved.",
  },
  {
    id: "cignall-butt-out-2018",
    label: "Butt Out Day with Great Flavours café · 1 March 2018",
    publisher: "Cignall Frankston",
    kind: "social",
    url: "https://www.facebook.com/cignall/posts/raff-and-bree-from-great-flavours-caf%C3%A9-in-frankston-loved-our-butt-out-day-so-mu/10156337234774586/",
    retrievedOn: "2026-08-22",
    note: "Documents one local café collaboration and litter-awareness promotion. It is not evidence of a broader or continuing community program.",
  },
  {
    id: "cignall-2019-win",
    label: "Hardworking St Albans man ‘too busy’ to collect $3.3 million TattsLotto prize",
    publisher: "Public repost of The Lott release",
    kind: "social",
    url: "https://www.facebook.com/groups/529582147502825/posts/681048992356139/",
    retrievedOn: "2026-08-22",
    note: "Search indexing attributes the ticket to Smokey's Frankston House Lotto, 8 Thompson Street; the readable page is partly obscured by login, so the attribution remains strongly supported rather than fully retrieved.",
  },
  {
    id: "lottery-3945-results",
    label: "Saturday Lotto draw 3945 results · 11 May 2019",
    publisher: "Oz Lotteries",
    kind: "public-record",
    url: "https://www.ozlotteries.com/saturday-lotto/results/draw/3945",
    retrievedOn: "2026-08-22",
    note: "Corroborates draw 3945, six Division One winners and the $3,333,333.34 dividend; the retailer attribution comes from the separately identified release/repost.",
  },
  {
    id: "lott-2022-million",
    label: "Coffee run leads to $1 million TattsLotto discovery for Rosebud man",
    publisher: "The Lott",
    kind: "official",
    url: "https://www.thelott.com/real-winners/saturday-lotto/coffee-run-leads-to-winning-discovery",
    retrievedOn: "2026-08-22",
    note: "Documents Division One, draw 4223, the 8 January 2022 draw and the ticket sold at 8 Thompson Street. It does not state the win's sequence position within the ten.",
  },
  {
    id: "shop-facebook-profile",
    label: "Cignall Frankston public profile",
    publisher: "Cignall Frankston",
    kind: "social",
    url: "https://www.facebook.com/cignall/",
    retrievedOn: "2026-08-22",
    note: "Current self-published profile wording documents the address, Archie, and the advertised services: TattsLotto, newspapers, tobacco, dry cleaning and house-key cutting. It does not date when each service began or ended.",
  },
  {
    id: "lott-2021-towerhill",
    label: "‘Completely normal’ Frankston couple turned into overnight millionaires",
    publisher: "The Lott Media Centre",
    kind: "official",
    url: "https://mediacentre.thelott.com/media-releases/franskton-couple-turned-into-overnight-millionaires-thanks-to-tattslotto-division-one-win/",
    retrievedOn: "2026-08-22",
    note: "Documents draw 4147 and Towerhill Lotto, 145 Frankston–Flinders Road. The winners lived in Frankston, but the ticket was not sold at 8 Thompson Street.",
  },
  {
    id: "lott-2025-beach-street",
    label: "Frankston dad plans to pay it forward with $1.2 million TattsLotto payday",
    publisher: "The Lott",
    kind: "official",
    url: "https://www.thelott.com/real-winners/saturday-lotto/frankston-dad-plans-to-pay-it-forward",
    retrievedOn: "2026-08-22",
    note: "Identifies Beach Street Newsagency, 237 Beach Street. Frankston residence is not 8 Thompson Street attribution.",
  },
  {
    id: "lott-2025-tsg-bayside",
    label: "Frankston woman's ordinary day turns extraordinary following $900,000 TattsLotto win",
    publisher: "The Lott",
    kind: "official",
    url: "https://www.thelott.com/real-winners/saturday-lotto/frankston-womans-ordinary-day-turns-extraordinary-following-tattslotto-win",
    retrievedOn: "2026-08-22",
    note: "Identifies TSG Bayside rather than the researched outlet. Frankston residence is not 8 Thompson Street attribution.",
  },
  {
    id: "lott-2026-tenth-win",
    label: "Frankston man's $3.1 million TattsLotto phone call burns more calories than his workout",
    publisher: "The Lott",
    kind: "official",
    url: "https://www.thelott.com/real-winners/saturday-lotto/frankston-mans-tattslotto-phone-call-burns-more-calories-than-his-workout",
    retrievedOn: "2026-08-22",
    note: "Names the outlet, address, tenth Division One sale and thirty-year milestone. Its indexed prize figure conflicts by $1,000 with two readable draw archives.",
  },
  {
    id: "lotterywest-4685",
    label: "Saturday Lotto draw 4685 results · 13 June 2026",
    publisher: "Lotterywest",
    kind: "official",
    url: "https://www.oz.lotterywest.com/saturday-lotto/results/draw/4685",
    retrievedOn: "2026-08-22",
    note: "Documents the $3,127,800.49 Division One dividend and two winners.",
  },
  {
    id: "ozlotteries-4685",
    label: "TattsLotto draw 4685 results · 13 June 2026",
    publisher: "Oz Lotteries",
    kind: "public-record",
    url: "https://www.ozlotteries.com/saturday-lotto/results/draw/4685",
    retrievedOn: "2026-08-22",
    note: "Independently displays the same $3,127,800.49 Division One dividend and two winners.",
  },
  {
    id: "cignall-2026-win",
    label: "Our shop has done it again — ten first-division wins",
    publisher: "Cignall Frankston",
    kind: "social",
    url: "https://www.facebook.com/cignall/posts/our-shop-has-done-it-again-ten-1st-division-wins-we-really-are-the-lucky-monkey-/1443132590954293/",
    retrievedOn: "2026-08-22",
    note: "Retailer-side contemporary post corroborating the outlet, address, tenth-win framing and winner story.",
  },
];
