export type VisualArchiveChapterId =
  | "originals"
  | "thirty-a"
  | "thirty-b"
  | "australian-a"
  | "australian-b"
  | "timeline";

export type VisualArchiveChapter = {
  id: VisualArchiveChapterId;
  label: string;
  shortLabel: string;
};

export type VisualArchiveItem = {
  id: string;
  number: number;
  chapter: VisualArchiveChapterId;
  title: string;
  mood: string;
  status: "Original reference" | "Creative study";
  src: string;
  width: number;
  height: number;
  alt: string;
  commentary: string;
};

export const visualArchiveChapters: readonly VisualArchiveChapter[] = [
  { id: "originals", label: "Original references", shortLabel: "Originals" },
  { id: "thirty-a", label: "Thirty Years · Set A", shortLabel: "30 Years A" },
  { id: "thirty-b", label: "Thirty Years · Set B", shortLabel: "30 Years B" },
  { id: "australian-a", label: "Australian characters · Set A", shortLabel: "Australia A" },
  { id: "australian-b", label: "Australian characters · Set B", shortLabel: "Australia B" },
  { id: "timeline", label: "Timeline experiments", shortLabel: "Timeline" },
];

export const visualArchiveItems: readonly VisualArchiveItem[] = [
  {
    id: "group-poster",
    number: 1,
    chapter: "originals",
    title: "The Thirty-Year Group Poster",
    mood: "Archive anchor",
    status: "Original reference",
    src: "/images/ziggy/legacy-44/01-ziggy-30-years-group-poster.webp",
    width: 1229,
    height: 1536,
    alt: "Black and gold Monkey Shop thirty-year poster with Ziggy and six people arranged around him",
    commentary:
      "This supplied image sets the whole visual grammar: black, cream, gold, a broad grin and an anniversary large enough to need its own weather system. The faces belong to this reference; the archive does not quietly promote them into identified staff without Rob and Carla saying so.",
  },
  {
    id: "tray-reference",
    number: 2,
    chapter: "originals",
    title: "The Monkey With the Tray",
    mood: "Physical reference",
    status: "Original reference",
    src: "/images/ziggy/legacy-44/02-ziggy-original-tray-reference.webp",
    width: 1024,
    height: 1536,
    alt: "Full-length reference of the smiling monkey figure in a harlequin vest holding a silver tray",
    commentary:
      "The physical anchor. Before the sainthood, premiership, bushranging and late-night television career, there was a monkey in gold trousers holding a tray with unnerving professional confidence. Every later Ziggy should still be traceable back to this silhouette.",
  },
  {
    id: "cabinet-thirty-years",
    number: 3,
    chapter: "thirty-a",
    title: "Cabinet of Thirty Years",
    mood: "Museum theatre",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/03-ziggy-cabinet-of-30-years.webp",
    width: 1122,
    height: 1402,
    alt: "Ornate illuminated cabinet filled with Monkey Shop memories and Ziggy behind the counter",
    commentary:
      "A shop window promoted to museum cabinet, with every drawer apparently holding a year, a customer or something nobody has labelled properly. The idea is strong because it treats ordinary shop life as worth keeping; the contents are atmosphere, not an inventory of proven objects.",
  },
  {
    id: "oracle-thompson-street",
    number: 4,
    chapter: "thirty-a",
    title: "Oracle of Thompson Street",
    mood: "Penny-arcade solemnity",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/04-ziggy-oracle-of-thompson-street.webp",
    width: 1122,
    height: 1402,
    alt: "Ziggy as a Thompson Street fortune teller behind a crystal ball in an ornate cabinet",
    commentary:
      "At last, a fortune teller whose main qualification is already owning a tray. The cabinet gives Ziggy permission to interpret the archive, but not to rewrite it: he may foresee your afternoon; he may not invent the shop’s opening date.",
  },
  {
    id: "split-era",
    number: 5,
    chapter: "thirty-a",
    title: "1996 / 2026 — Same Monkey, Different Light",
    mood: "Then and now",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/05-ziggy-1996-2026-split-era.webp",
    width: 1122,
    height: 1402,
    alt: "Split-era poster placing Ziggy between imagined 1996 and 2026 Monkey Shop streetscapes",
    commentary:
      "A clean anniversary device: old Frankston on one side, present Frankston on the other, Ziggy standing in the seam as if he personally supervised the transition. It reads beautifully, but it is an imagined bridge between eras—not a photographic comparison.",
  },
  {
    id: "after-closing",
    number: 6,
    chapter: "thirty-a",
    title: "After Closing",
    mood: "Quietly haunted",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/06-ziggy-after-closing.webp",
    width: 1122,
    height: 1402,
    alt: "Ziggy standing alone with his tray outside a dark Monkey Shop after closing",
    commentary:
      "No customers, no confetti, no grand mythology—just the figure, the window and the wet dark after everybody has gone home. It is one of the quieter studies, and one of the best: local legends also spend most of their lives waiting under ordinary lights.",
  },
  {
    id: "thirty-year-receipt",
    number: 7,
    chapter: "thirty-a",
    title: "The Thirty-Year Receipt",
    mood: "Bureaucratic slapstick",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/07-ziggy-thirty-year-receipt.webp",
    width: 1122,
    height: 1402,
    alt: "Ziggy holding an impossibly long commemorative receipt spilling from an old cash register",
    commentary:
      "Thirty years itemised until the docket becomes a practical tripping hazard. The gag is bureaucratic but affectionate: thousands of small transactions accumulate into a history no single receipt could contain. No GST calculation should be attempted from this image.",
  },
  {
    id: "saint-ziggy",
    number: 8,
    chapter: "thirty-a",
    title: "Saint Ziggy of Frankston",
    mood: "Ceremonial nonsense",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/08-saint-ziggy-of-frankston.webp",
    width: 1122,
    height: 1402,
    alt: "Gold devotional poster depicting Ziggy as the fictional patron saint of Frankston",
    commentary:
      "Patron saint of good service, local customers and the till that refuses to stop down Thompson Street. The halo is pure theatre; the underlying tribute is sincere. Canonisation remains pending, largely because the paperwork was placed on the tray and nobody picked it up.",
  },
  {
    id: "reflection-closeup",
    number: 9,
    chapter: "thirty-a",
    title: "The Grin, Examined",
    mood: "Character close-up",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/09-ziggy-reflection-closeup.webp",
    width: 1122,
    height: 1402,
    alt: "Extreme close portrait of Ziggy smiling in the warm light of the memory cabinet",
    commentary:
      "The ears enter first, the bow tie tries to restore order, and the teeth have already clocked on. Up close, Ziggy is less a mascot than a piece of shop furniture that has developed opinions and chosen not to share them.",
  },
  {
    id: "oracle-cards",
    number: 10,
    chapter: "thirty-a",
    title: "The Monkey Shop Tarot",
    mood: "Object mythology",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/10-ziggy-oracle-tarot-cards.webp",
    width: 1122,
    height: 1402,
    alt: "Six ornate fictional tarot cards featuring Ziggy, the shopkeeper, the regular and Monkey Shop objects",
    commentary:
      "The Shopkeeper, The Regular, The Last Minute Gift, The Window, The Receipt and The Monkey: six sacred stations of retail life. Not a predictive system so much as a very elaborate way of admitting the same people and objects keep coming back.",
  },
  {
    id: "archaeological-discovery",
    number: 11,
    chapter: "thirty-a",
    title: "Archaeological Discovery",
    mood: "Future-history farce",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/11-ziggy-archaeological-discovery.webp",
    width: 1122,
    height: 1402,
    alt: "Imagined archaeologists excavating a buried Ziggy figure and Monkey Shop artefacts",
    commentary:
      "Future archaeologists uncover Frankston’s ceremonial monkey and immediately mislabel everything except the tray. It is the archive’s favourite warning in comic form: an object can survive perfectly while its meaning wanders off without supervision.",
  },
  {
    id: "snow-globe",
    number: 12,
    chapter: "thirty-a",
    title: "Ziggy’s Snow Globe",
    mood: "Tender souvenir",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/12-ziggy-snow-globe.webp",
    width: 1122,
    height: 1402,
    alt: "Golden Monkey Shop streetscape and Ziggy contained inside a commemorative snow globe",
    commentary:
      "A whole shop world reduced to one object you can shake without breaking it. The danger of nostalgia is turning a living place into a sealed souvenir; the charm here is that Ziggy still looks ready to step out and serve whoever is next.",
  },
  {
    id: "king-kong",
    number: 13,
    chapter: "thirty-b",
    title: "Frankston King Kong",
    mood: "Matinee slapstick",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/13-ziggy-frankston-king-kong-poster.webp",
    width: 1122,
    height: 1402,
    alt: "Vintage monster-movie poster showing a giant polite Ziggy towering over Frankston with his tray",
    commentary:
      "He is enormous, impeccably polite and still carrying the tray. That is the whole joke and it lands cleanly: Frankston gets a giant movie monster whose only destructive impulse is excessive customer service.",
  },
  {
    id: "fortune-machine",
    number: 14,
    chapter: "thirty-b",
    title: "The Penny-Arcade Fortune Machine",
    mood: "Playable folklore",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/14-ziggy-penny-arcade-fortune-machine.webp",
    width: 1122,
    height: 1402,
    alt: "Ornate one-cent Ziggy fortune machine with crank, lights, tray and printed fortune slot",
    commentary:
      "One penny, one crank, one answer delivered with more confidence than the evidence warrants. This study became the clearest bridge between the physical monkey and Ask Ziggy: a shop-window figure that does not merely stand there, but issues paperwork.",
  },
  {
    id: "blueprint-automaton",
    number: 15,
    chapter: "thirty-b",
    title: "Hospitality Automaton — Patent Pending",
    mood: "Technical deadpan",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/15-ziggy-blueprint-automaton.webp",
    width: 1122,
    height: 1402,
    alt: "Fictional vintage patent drawing showing front, side and mechanical details of the Ziggy automaton",
    commentary:
      "The institution finally studies the machine: ear assemblies, grin mechanism, tray arm and a premium hospitality core of uncertain legality. It explains everything except why a completely motionless figure can still look like he knows you are late.",
  },
  {
    id: "thirty-ziggys",
    number: 16,
    chapter: "thirty-b",
    title: "Thirty Ziggys",
    mood: "Annual identity crisis",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/16-thirty-ziggys-1996-2025.webp",
    width: 1122,
    height: 1402,
    alt: "Grid of thirty imagined annual Ziggy portraits from 1996 to 2025",
    commentary:
      "Thirty costumes attempt to explain thirty years and accidentally prove the opposite: the grin, ears and service pose survive every disguise. The years are a creative sequence, not a factual wardrobe chronology—Ziggy did not actually spend 2007 dressed like that, as far as the archive knows.",
  },
  {
    id: "polaroid-archive",
    number: 17,
    chapter: "thirty-b",
    title: "The Polaroid Archive",
    mood: "Imagined memory",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/17-ziggy-polaroid-archive.webp",
    width: 1122,
    height: 1402,
    alt: "Tabletop arrangement of imagined Ziggy Polaroids labelled across thirty years",
    commentary:
      "It looks like a family archive because it understands the emotional shape of one: bent corners, handwritten years and people returning to the frame. None of these are real documentary photographs. Its best use is showing exactly where the real candid pictures will matter most when they arrive.",
  },
  {
    id: "night-bus",
    number: 18,
    chapter: "thirty-b",
    title: "The Night Bus Home",
    mood: "After-hours melancholy",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/18-ziggy-night-bus-home.webp",
    width: 1122,
    height: 1402,
    alt: "Ziggy sitting alone with his tray at a rainy Frankston bus stop at night",
    commentary:
      "Even a local legend has to get home. The tray sits on his knees like one last customer he has promised not to spill, while Frankston glows wet and ordinary around him. Funny on first look; oddly tender on the second.",
  },
  {
    id: "last-customer",
    number: 19,
    chapter: "thirty-b",
    title: "The Last Customer, 2096",
    mood: "Science-fiction loyalty",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/19-ziggy-last-customer-2096.webp",
    width: 1122,
    height: 1402,
    alt: "Futuristic Frankston street in 2096 with Ziggy serving a final hooded customer outside the Monkey Shop",
    commentary:
      "A hundred-year shop, one final sale and a monkey still refusing to knock off early. The date is pure speculation; the feeling is not. Longevity is imagined here as the same small gesture repeated until the whole city changes around it.",
  },
  {
    id: "shop-window-dream",
    number: 20,
    chapter: "thirty-b",
    title: "Shop Window Dream",
    mood: "Surreal local folklore",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/20-ziggy-shop-window-dream.webp",
    width: 1122,
    height: 1402,
    alt: "Dreamlike Monkey Shop window with floating receipts, moons, signs, clocks and Ziggy holding his tray",
    commentary:
      "The window has gone to sleep and started remembering everything at once: receipts float, clocks loosen and thirty years refuse to remain in chronological order. Ziggy, naturally, is awake. Somebody has to hold the tray while reality takes five.",
  },
  {
    id: "trading-card",
    number: 21,
    chapter: "thirty-b",
    title: "Legendary Shop Guardian",
    mood: "Collectible bravado",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/21-ziggy-trading-card-shop-guardian.webp",
    width: 1122,
    height: 1402,
    alt: "Gold Ziggy trading card with fictional attributes, statistics and limited-edition numbering",
    commentary:
      "Loyalty 100. Wisdom 92. Charm 98. Tray discipline apparently too advanced for the card printer. The fake statistics are gloriously unnecessary, but the format makes a useful point: Ziggy already behaves like a character people might collect.",
  },
  {
    id: "commemorative-stamp",
    number: 22,
    chapter: "thirty-b",
    title: "Thirty-Year Commemorative Stamp",
    mood: "Pocket ceremony",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/22-ziggy-thirty-year-commemorative-stamp.webp",
    width: 1122,
    height: 1402,
    alt: "Ornate fictional thirty-year postage stamp featuring Ziggy, Thompson Street and Frankston",
    commentary:
      "A whole anniversary compressed into something small enough to lick, lose or find in a drawer in twenty years. It has the seriousness of an official issue and absolutely none of the approval: Australia Post has not, to our knowledge, placed this creature into circulation.",
  },
  {
    id: "old-vic-gentleman",
    number: 23,
    chapter: "australian-a",
    title: "Gentleman of the Old Vic State",
    mood: "Straight-faced fiction",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/23-ziggy-gentleman-of-the-old-vic-state.webp",
    width: 1122,
    height: 1402,
    alt: "Ziggy dressed as a Victorian gentleman in a fictional Old Vic State poster",
    commentary:
      "Impeccably Victorian, geographically Frankston and constitutionally nonexistent. Old Vic State works best exactly here: the pose is grave, the paperwork is beautiful, and the monkey remains the only official who remembers to bring a tray.",
  },
  {
    id: "bushranger",
    number: 24,
    chapter: "australian-a",
    title: "The Infamous Bushranger",
    mood: "Wanted-poster farce",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/24-ziggy-bushranger.webp",
    width: 1122,
    height: 1402,
    alt: "Sepia bushranger poster showing Ziggy with a metal helmet, cape and tray",
    commentary:
      "He blocks the track, raises the tray and politely demands one penny for administrative purposes. Notorious since 1996, allegedly; no convictions, no getaway horse and no evidence the helmet fits over those ears.",
  },
  {
    id: "cricket-legend",
    number: 25,
    chapter: "australian-a",
    title: "Australia’s Cricket Legend",
    mood: "Sporting folklore",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/25-ziggy-cricket-legend.webp",
    width: 1122,
    height: 1402,
    alt: "Vintage cricket poster with Ziggy in cap and knitted vest holding his tray on a cricket ground",
    commentary:
      "Gentleman, entertainer, legend—and apparently selected without bat, ball or visible concern. The tray suggests an unusual fielding technique, though opposing sides have struggled to lodge a complaint while he keeps smiling like that.",
  },
  {
    id: "king-outback",
    number: 26,
    chapter: "australian-a",
    title: "King of the Outback",
    mood: "Adventure serial",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/26-ziggy-king-of-the-outback.webp",
    width: 1122,
    height: 1402,
    alt: "Ziggy in explorer clothes holding his tray in a dramatic red outback landscape",
    commentary:
      "Survival of the cheekiest: hat, boots, four-wheel drive and one silver serving tray carried deep into country for reasons the expedition log declines to explain. A majestic image of preparedness, provided the emergency involves snacks.",
  },
  {
    id: "bush-mechanic",
    number: 27,
    chapter: "australian-a",
    title: "The Bush Mechanic",
    mood: "Grease-and-wire competence",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/27-ziggy-bush-mechanic.webp",
    width: 1122,
    height: 1402,
    alt: "Ziggy as a bush mechanic beside an old vehicle, using his tray as a parts bowl",
    commentary:
      "At last the tray receives accredited vocational training and becomes a parts bowl. Ziggy can fix anything with wire, optimism and one bolt left over. If the engine still refuses, the official diagnosis is ‘bit ordinary’ and everyone goes for tea.",
  },
  {
    id: "tram-conductor",
    number: 28,
    chapter: "australian-a",
    title: "Melbourne Tramway Welcome",
    mood: "Civic hospitality",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/28-ziggy-melbourne-tram-conductor.webp",
    width: 1122,
    height: 1402,
    alt: "Ziggy dressed as a tram conductor standing at a vintage green and yellow Melbourne tram",
    commentary:
      "Fares please, manners optional, tray inexplicably mandatory. The conductor uniform suits him because both jobs rely on standing in a familiar place, greeting everybody and knowing more about the route than passengers do.",
  },
  {
    id: "tv-grande-dame",
    number: 29,
    chapter: "australian-a",
    title: "Australia’s TV Grande Dame",
    mood: "Full-volume camp",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/29-ziggy-australian-tv-grande-dame.webp",
    width: 1122,
    height: 1402,
    alt: "Ziggy on a glittering television stage in a purple wig and sequined jacket",
    commentary:
      "Purple hair, sequins, live audience, no reduction in tray service. This is Ziggy at Full Zig: the character consumes the entire studio, calls everyone darling and somehow leaves the prop department feeling underdressed.",
  },
  {
    id: "wildlife-presenter",
    number: 30,
    chapter: "australian-a",
    title: "Wild Australia With Ziggy",
    mood: "Educational mischief",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/30-ziggy-wildlife-presenter.webp",
    width: 1122,
    height: 1402,
    alt: "Ziggy as a wildlife presenter in the Australian bush pointing beside native animals",
    commentary:
      "Respect, protect, preserve: scientifically sound advice from a monkey with a small jurisdictional problem. He points confidently into the bush while the wildlife appears to be conducting its own assessment of the presenter.",
  },
  {
    id: "prime-minister",
    number: 31,
    chapter: "australian-a",
    title: "Prime Minister Ziggy",
    mood: "Institutional deadpan",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/31-prime-minister-ziggy.webp",
    width: 1122,
    height: 1402,
    alt: "Fictional official portrait of Ziggy at a prime ministerial lectern with Australian flags",
    commentary:
      "The policy platform is ‘one tray at a time,’ which remains more legible than several real platforms. This is political theatre only—no government identity, endorsement or constitutional emergency is implied, despite the extremely official carpeting.",
  },
  {
    id: "eighties-tv",
    number: 32,
    chapter: "australian-a",
    title: "Saturday Night Spectacular",
    mood: "Neon variety hour",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/32-ziggy-1980s-tv-personality.webp",
    width: 1122,
    height: 1402,
    alt: "Neon 1980s television poster with Ziggy holding a microphone and tray in a lavender suit",
    commentary:
      "A microphone in one hand, the tray in the other and enough neon to power Carrum Downs. He welcomes you to the show, promises great music and resolves every production crisis by throwing to a sponsor nobody remembers.",
  },
  {
    id: "footy-legend",
    number: 33,
    chapter: "australian-b",
    title: "The Footy Legend",
    mood: "Mud-soaked mythology",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/33-ziggy-footy-legend.webp",
    width: 1122,
    height: 1402,
    alt: "Vintage football poster with Ziggy in a muddy guernsey holding an Australian rules football",
    commentary:
      "Three hundred games, thirty seasons, never delisted: the statistics are entirely unverified, but the calves are beyond dispute. He looks ready to play four quarters, accept the cup and return to the counter before closing.",
  },
  {
    id: "surf-lifesaver",
    number: 34,
    chapter: "australian-b",
    title: "The Surf Lifesaver",
    mood: "Public-service slapstick",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/34-ziggy-surf-lifesaver.webp",
    width: 1122,
    height: 1402,
    alt: "Bright retro beach poster with Ziggy in red and yellow surf lifesaving uniform holding a rescue tray",
    commentary:
      "The rescue tray is hydrodynamically questionable; the community message is perfectly sound. Swim between the flags, shop between the signs and never turn your back on a grinning primate carrying circular metal equipment.",
  },
  {
    id: "goldfields",
    number: 35,
    chapter: "australian-b",
    title: "Ziggy of the Goldfields",
    mood: "Prospecting providence",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/35-ziggy-goldfields-prospector.webp",
    width: 1122,
    height: 1402,
    alt: "Sepia goldfields poster with prospector Ziggy holding a pan containing a gold nugget",
    commentary:
      "After dozens of creative assignments, somebody finally gives the tray a job it was born to do. Dig deep, dream big, strike it rich—or at least find enough colour in the pan to justify another cup of tea.",
  },
  {
    id: "swagman",
    number: 36,
    chapter: "australian-b",
    title: "The Swagman",
    mood: "Roadside ballad",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/36-ziggy-the-swagman.webp",
    width: 1122,
    height: 1402,
    alt: "Sepia bush poster of Ziggy walking as a swagman with bedroll, billy and tray",
    commentary:
      "Not all who wander are lost; some are simply carrying too many circular objects. The swag, billy and tray make him look self-sufficient, though the bow tie suggests he still expects table service somewhere beyond the next gum tree.",
  },
  {
    id: "suburban-publican",
    number: 37,
    chapter: "australian-b",
    title: "The Suburban Publican",
    mood: "Locals’ local",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/37-ziggy-suburban-publican.webp",
    width: 1122,
    height: 1402,
    alt: "Ziggy as a smiling suburban publican in a warm Australian hotel bar",
    commentary:
      "The tray has returned to its natural habitat. Everyone knows Ziggy, Ziggy knows everyone, and the carpet contains information that will not be released during this inquiry. No actual liquor licence or historic pub career is claimed.",
  },
  {
    id: "station-master",
    number: 38,
    chapter: "australian-b",
    title: "The Frankston Station Character",
    mood: "Midnight local folklore",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/38-ziggy-frankston-station-master.webp",
    width: 1122,
    height: 1402,
    alt: "Ziggy dressed as a station master on a wet Frankston railway platform at night",
    commentary:
      "Last train, 11:47 pm. Ziggy is still here. Rain, platform lights and the familiar face turn the image into proper local folklore: half civic portrait, half the person you are relieved to see when the timetable has given up.",
  },
  {
    id: "explorer",
    number: 39,
    chapter: "australian-b",
    title: "The Australian Explorer",
    mood: "Heroic obviousness",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/39-ziggy-australian-explorer.webp",
    width: 1122,
    height: 1402,
    alt: "Heroic Ziggy explorer pointing across an Australian mountain landscape while holding his tray",
    commentary:
      "Thirty years of discovering the obvious: Frankston is that way, the shop is back there and somebody has left the kettle on. Courage, direction and destiny are supplied in abundance; new geographical findings remain limited.",
  },
  {
    id: "weather-man",
    number: 40,
    chapter: "australian-b",
    title: "The Weather Man",
    mood: "Forecast-grade certainty",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/40-ziggy-retro-weather-man.webp",
    width: 1122,
    height: 1402,
    alt: "Colourful retro television weather map with Ziggy presenting an Australian forecast",
    commentary:
      "Might rain. Might shine. Either way, it’ll be right. This is both a meteorological masterpiece and a complete liability waiver, delivered beside a map on which Frankston has sensibly been given more attention than the rest of the continent.",
  },
  {
    id: "returned-local-hero",
    number: 41,
    chapter: "australian-b",
    title: "The Returned Local Hero",
    mood: "Quiet honour",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/41-ziggy-returned-local-hero.webp",
    width: 1122,
    height: 1402,
    alt: "Formal portrait of Ziggy in a navy blazer with medals, holding his tray in a civic room",
    commentary:
      "Here the joke pulls back. The image is about service, return and belonging—the dignity a place gives a familiar figure after enough years. The medals and biography are imagined, so the feeling may stand without being mistaken for a record.",
  },
  {
    id: "australian-of-year",
    number: 42,
    chapter: "australian-b",
    title: "Australian of the Year",
    mood: "National ceremony",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/42-ziggy-australian-of-the-year.webp",
    width: 1122,
    height: 1402,
    alt: "Formal gold and black Australian of the Year stage portrait of Ziggy in evening dress",
    commentary:
      "National stage, evening dress, ornamental foliage—and the tray is still on shift. The honour is fictional, the posture is extremely official, and the grin suggests he has already thanked Frankston before the orchestra could play him off.",
  },
  {
    id: "timeline-collage-a",
    number: 43,
    chapter: "timeline",
    title: "Thirty-Year Timeline — Study A",
    mood: "Maximum chronology",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/43-ziggy-30-year-timeline-collage-a.webp",
    width: 1536,
    height: 1024,
    alt: "Wide poster grid of thirty imagined annual Ziggy scenes from 1996 to 2025",
    commentary:
      "The first attempt to make thirty years sit still inside one grid. Every year receives a costume, prop or mood, which is visually useful and historically impossible. Read it as a rhythm study for a timeline, never as evidence of what happened in any labelled year.",
  },
  {
    id: "timeline-collage-b",
    number: 44,
    chapter: "timeline",
    title: "Thirty-Year Timeline — Study B",
    mood: "The final contact sheet",
    status: "Creative study",
    src: "/images/ziggy/legacy-44/44-ziggy-30-year-timeline-collage-b.webp",
    width: 1536,
    height: 1024,
    alt: "Second wide black and gold grid of imagined Ziggy scenes labelled from 1996 to 2026",
    commentary:
      "A slightly calmer second pass: still thirty years, still one grin, still far too much history for forty-four little rectangles. Its job is to suggest the scale of the anniversary and point toward real milestones—not to stand in for them. End of tray. Beginning of archive.",
  },
];
